### ISSUE TITLE
可否提供一下使用范例？

### ISSUE THREAD

**Issue by Pzoom522** [escse/spider-for-163music#1]
想使用里面的“在评论中搜索用户”这一功能。可否给一个“主函数”的范例？因为源代码注释较少，不易理解如何调用。感谢！

**Comment by escse** [comment]
Hi，没想到居然有人关注这个repo。这个repo也是在zhihu那个问题的基础上写的
代码写得很差，见谅。还有一些小bug没解决，仅供参考哈。
关于你的问题，我已经在readme页面上补充了2个简单的使用方法
欢迎提出代码或者功能上的建议！
